import { createContext, useContext, useEffect, useState } from 'react'

const STORAGE_KEY = 'recipe-app-lang'

const translations = {
  en: {
    // App
    loading: 'Loading…',
    // Login
    appTitle: 'Recipe Translator',
    tagline: 'Translate recipes to your language',
    login: 'Log in',
    register: 'Register',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm password',
    showPassword: 'Show password',
    hidePassword: 'Hide password',
    passwordsMismatch: 'Passwords do not match',
    passwordTooShort: 'Password must be at least 8 characters',
    logInButton: 'Log in →',
    createAccountButton: 'Create account →',
    // Navbar
    appSubtitle: 'Recipe translation',
    shoppingList: 'Shopping list',
    recipesQuota: 'Recipes: {{used}}/{{limit}}',
    recipesQuotaUnlimited: 'Recipes: ∞',
    settings: 'Settings',
    logOut: 'Log out',
    // Settings
    translationAndLocation: 'Translation and location',
    appLanguage: 'App / website language',
    recipeLanguage: 'Recipe language',
    cookingAndDiet: 'Cooking & diet',
    defaultServingsLabel: 'I usually cook for…',
    defaultServingsHint: 'Used as your default when scaling recipes (coming soon).',
    people: 'people',
    allergensToAvoid: 'Allergens to avoid',
    otherAllergens: 'Other allergens (free text)',
    otherAllergensPlaceholder: 'e.g. kiwi, strawberries, specific brand…',
    otherAllergensHint: 'We will treat these as “avoid” terms (best effort) when suggesting/adapting recipes.',
    optional: 'optional',
    sourceLanguage: 'Source language',
    translateTo: 'Translate to',
    language: 'Language',
    country: 'Country',
    city: 'City',
    hintLanguage: 'e.g. pl',
    hintCountry: 'e.g. PL',
    hintCity: 'e.g. London',
    saveSettings: 'Save settings',
    saving: 'Saving…',
    saved: 'Saved',
    account: 'Account',
    joined: 'Joined',
    verified: 'verified',
    unverified: 'unverified',
    resendVerification: 'Resend verification email',
    deleteAccount: 'Delete account',
    deleteAccountConfirm: 'Permanently delete your account and all recipes. Type DELETE to confirm.',
    typeDelete: 'Type DELETE',
    deleting: 'Deleting…',
    deleteAccountButton: 'Delete account',
    fetchStarterRecipes: 'Starter recipes',
    fetchStarterRecipesHint: 'Add 3 starter recipes from famous cooks in your country if you have none (e.g. if onboarding was skipped or failed).',
    fetchStarterRecipesButton: 'Fetch starter recipes',
    fetchStarterRecipesDone: 'Starter recipes added (or you already had recipes).',
    // AddRecipeModal
    addRecipe: 'Add recipe',
    pasteRecipeUrlOrText: 'Paste recipe URL or text',
    pasteText: 'Paste text',
    pasteUrl: 'Paste URL',
    placeholderRecipe: 'Paste your recipe here…',
    translating: 'Translating…',
    translatingNote: 'Translating… this may take a few seconds.',
    cancel: 'Cancel',
    translateButton: 'Translate →',
    urlError: 'Could not fetch URL. Check the link and try again.',
    urlInvalid: 'Enter a valid URL (http:// or https://)',
    // Verify
    emailVerification: 'Email verification',
    checkingToken: 'Checking your verification token…',
    verifySuccess: 'Your email has been verified. You can use the app.',
    verifyError: 'Failed to verify email.',
    missingToken: 'Missing verification token.',
    verificationEmailSent: 'A verification email has been sent. Please check your inbox.',
    goToApp: 'Go to app',
    backToHome: 'Back to home',
    // RecipeList
    onShoppingList: 'On shopping list',
    addToList: 'Add to list',
    favorites: 'favorites',
    deleteRecipe: 'Delete recipe',
    addYourFirstRecipe: 'Add your first recipe',
    emptyCookbookTitle: 'Your cookbook is empty',
    emptyCookbookSubtitle: 'Paste a recipe and we will translate it and adapt ingredients for your market.',
    myRecipes: 'My recipes',
    noRecipes: 'No recipes',
    searchRecipes: 'Search recipes…',
    search: 'Search',
    clear: 'Clear',
    noSearchResults: 'No recipes match your search.',
    whatCanIMake: 'What can I make?',
    whatCanIMakeNav: 'What can I make?',
    whatCanIMakeHint: 'Enter ingredients you have and we’ll find matching recipes.',
    ingredientsIHave: 'Ingredients I have',
    ingredientsPlaceholder: 'e.g. chicken, lemon, rice',
    ingredientsCommaOrNewline: 'Separate by comma or new line.',
    dietFilters: 'Diet',
    assumePantry: 'Assume I have basic pantry (salt, sugar, oil, etc.)',
    source: 'Search in',
    findRecipes: 'Find recipes',
    finding: 'Finding…',
    youHaveEverything: 'You have everything to make this.',
    missingIngredients: 'Missing',
    iHaveThis: 'I have this',
    noMatchingRecipes: 'No matching recipes.',
    tryMoreIngredientsOrSwitchAI: 'Try adding more ingredients or switch to AI suggestion.',
    addAtLeastOneIngredient: 'Add at least one ingredient.',
    somethingWentWrong: 'Something went wrong.',
    aiSuggestion: 'AI suggestion',
    noAISuggestions: 'No AI suggestions yet.',
    addToMyRecipes: 'Add to my recipes',
    addedToRecipes: 'Added',
    adding: 'Adding…',
    viewRecipe: 'View recipe',
    all: 'All',
    favoritesTab: 'Favorites',
    add: 'Add',
    noFavorites: 'No favorites',
    noFavoritesHint: 'Star a recipe to see it here',
    alreadyOnList: 'Recipe is already on the shopping list',
    addToFavorites: 'Add to favorites',
    removeFromFavorites: 'Remove from favorites',
    // RecipeDetail
    back: 'Back',
    adaptRecipe: 'Adapt recipe',
    relocalize: 'Re-localize',
    relocalizeHint: 'Re-translate and localize for your current settings',
    relocalized: 'Recipe re-localized',
    failedToRelocalize: 'Failed to re-localize recipe',
    original: 'Original',
    vegetarian: 'Vegetarian',
    vegan: 'Vegan',
    dairyFree: 'Dairy free',
    glutenFree: 'Gluten free',
    kosher: 'Kosher',
    halal: 'Halal',
    nutFree: 'Nut free',
    lowSodium: 'Low sodium',
    adapting: 'Adapting…',
    cannotAdapt: 'This recipe cannot be fully adapted to',
    chooseOption: 'Choose one of the options below:',
    generate: 'Generate',
    close: 'Close',
    translationInProgress: 'Translation in progress — content will appear shortly.',
    notes: 'Notes',
    adaptationSummary: 'What we changed',
    ingredients: 'Ingredients',
    alternativesFor: 'Alternatives for',
    loadingAlternatives: 'Loading alternatives…',
    noAlternativesFound: 'No alternatives found.',
    ingredientAlternatives: 'Ingredient alternatives',
    usesOneToken: 'Uses 1 token',
    enableIngredientLookup: 'Enable ingredient alternatives (uses credits)',
    translated: 'Translated',
    originalLabel: 'Original',
    instructions: 'Instructions',
    ingredientSubstitutions: 'Ingredient substitutions',
    myNotes: 'My notes',
    notesPlaceholder: 'Add your own notes, tips or modifications…',
    saveNotes: 'Save notes',
    recipeNotFound: 'Recipe not found',
    servings: 'Servings',
    prepTime: 'Prep time',
    cookTime: 'Cook time',
    failedToAdapt: 'Failed to adapt recipe.',
    failedToGenerateVariant: 'Failed to generate variant.',
    backToOriginal: 'Back to original',
    applyAdaptations: 'Apply',
    removeVariant: 'Remove version',
    showOriginal: 'Show original',
    hideOriginal: 'Hide original',
    addRecipePhoto: 'Add recipe photo',
    generateRecipePhoto: 'Generate photo',
    uploadRecipePhoto: 'Upload photo',
    removeRecipePhoto: 'Remove photo',
    // ShoppingListPanel
    recipe: 'recipe',
    recipesCount: 'recipes',
    listEmpty: 'List is empty',
    loadingIngredients: 'Loading ingredients…',
    betterSubstitute: 'Better substitute…',
    save: 'Save',
    suggestSubstitute: 'Suggest better substitute',
    clearList: 'Clear list',
    print: 'Print',
    sent: 'Sent!',
    sendToEmail: 'Send to email',
    sendFailed: 'Send failed',
    of: 'of',
    addRecipesToSeeIngredients: 'Add recipes to see ingredients',
    failedToClearList: 'Failed to clear list',
  },
  he: {
    loading: 'טוען…',
    appTitle: 'מתרגם מתכונים',
    tagline: 'תרגם מתכונים לשפה שלך',
    login: 'התחבר',
    register: 'הרשם',
    email: 'אימייל',
    password: 'סיסמה',
    confirmPassword: 'אימות סיסמה',
    showPassword: 'הצג סיסמה',
    hidePassword: 'הסתר סיסמה',
    passwordsMismatch: 'הסיסמאות אינן תואמות',
    passwordTooShort: 'הסיסמה חייבת להכיל לפחות 8 תווים',
    logInButton: 'התחבר ←',
    createAccountButton: 'צור חשבון ←',
    appSubtitle: 'תרגום מתכונים',
    shoppingList: 'רשימת קניות',
    recipesQuota: 'מתכונים: {{used}}/{{limit}}',
    recipesQuotaUnlimited: 'מתכונים: ∞',
    settings: 'הגדרות',
    logOut: 'התנתק',
    translationAndLocation: 'תרגום ומיקום',
    appLanguage: 'שפת האפליקציה / האתר',
    recipeLanguage: 'שפת המתכונים',
    cookingAndDiet: 'בישול ותזונה',
    defaultServingsLabel: 'בדרך כלל אני מבשל/ת עבור…',
    defaultServingsHint: 'ישמש כברירת מחדל בעת התאמת כמויות (בקרוב).',
    people: 'אנשים',
    allergensToAvoid: 'אלרגנים להימנע מהם',
    otherAllergens: 'אלרגנים אחרים (טקסט חופשי)',
    otherAllergensPlaceholder: 'למשל: קיווי, תותים, מותג ספציפי…',
    otherAllergensHint: 'נשתמש בזה כ״רשימת הימנעות״ (מאמץ סביר) בהצעות/התאמות מתכונים.',
    optional: 'אופציונלי',
    sourceLanguage: 'שפת מקור',
    translateTo: 'תרגם ל',
    language: 'שפה',
    country: 'מדינה',
    city: 'עיר',
    hintLanguage: 'למשל he',
    hintCountry: 'למשל IL',
    hintCity: 'למשל תל אביב',
    saveSettings: 'שמור הגדרות',
    saving: 'שומר…',
    saved: 'נשמר',
    account: 'חשבון',
    joined: 'הצטרף/ה',
    verified: 'מאומת',
    unverified: 'לא מאומת',
    resendVerification: 'שלח שוב אימייל אימות',
    deleteAccount: 'מחק חשבון',
    deleteAccountConfirm: 'מחיקת החשבון וכל המתכונים לצמיתות. הקלד DELETE לאישור.',
    typeDelete: 'הקלד DELETE',
    deleting: 'מוחק…',
    deleteAccountButton: 'מחק חשבון',
    fetchStarterRecipes: 'מתכוני התחלה',
    fetchStarterRecipesHint: 'הוסף 3 מתכוני התחלה ממטבחים מפורסמים במדינה שלך אם אין לך (למשל אם דילגת על ההתחלה).',
    fetchStarterRecipesButton: 'טען מתכוני התחלה',
    fetchStarterRecipesDone: 'מתכוני התחלה נוספו (או שכבר היו לך מתכונים).',
    addRecipe: 'הוסף מתכון',
    pasteRecipeUrlOrText: 'הדבק קישור או טקסט מתכון',
    pasteText: 'הדבק טקסט',
    pasteUrl: 'הדבק קישור',
    placeholderRecipe: 'הדבק את המתכון כאן…',
    translating: 'מתרגם…',
    translatingNote: 'מתרגם… זה עלול לקחת כמה שניות.',
    cancel: 'ביטול',
    translateButton: 'תרגם ←',
    urlError: 'לא ניתן לטעון את הקישור. בדוק ונסה שוב.',
    urlInvalid: 'הזן כתובת תקינה (http:// או https://)',
    emailVerification: 'אימות אימייל',
    checkingToken: 'בודק את קוד האימות…',
    verifySuccess: 'האימייל אומת. אפשר להשתמש באפליקציה.',
    verifyError: 'אימות האימייל נכשל.',
    missingToken: 'חסר קוד אימות.',
    verificationEmailSent: 'נשלח אימייל אימות. בדוק את תיבת הדואר.',
    goToApp: 'לאפליקציה',
    backToHome: 'בחזרה לדף הבית',
    onShoppingList: 'ברשימת הקניות',
    addToList: 'הוסף לרשימה',
    favorites: 'מועדפים',
    deleteRecipe: 'מחק מתכון',
    addYourFirstRecipe: 'הוסף את המתכון הראשון שלך',
    myRecipes: 'המתכונים שלי',
    noRecipes: 'אין מתכונים',
    searchRecipes: 'חיפוש מתכונים…',
    search: 'חפש',
    clear: 'נקה',
    noSearchResults: 'לא נמצאו מתכונים התואמים את החיפוש.',
    whatCanIMake: 'מה אני יכול להכין?',
    whatCanIMakeNav: 'מה אני יכול להכין?',
    whatCanIMakeHint: 'הזן מרכיבים שיש לך ונמצא מתכונים תואמים.',
    ingredientsIHave: 'מרכיבים שיש לי',
    ingredientsPlaceholder: 'למשל עוף, לימון, אורז',
    ingredientsCommaOrNewline: 'הפרד בפסיק או בשורה חדשה.',
    dietFilters: 'דיאטה',
    assumePantry: 'יש לי מצרכים בסיסיים (מלח, סוכר, שמן וכו\')',
    source: 'חפש ב',
    findRecipes: 'מצא מתכונים',
    finding: 'מחפש…',
    youHaveEverything: 'יש לך הכל להכנה.',
    missingIngredients: 'חסר',
    iHaveThis: 'יש לי',
    noMatchingRecipes: 'אין מתכונים תואמים.',
    tryMoreIngredientsOrSwitchAI: 'נסה להוסיף מרכיבים או לעבור להצעת AI.',
    addAtLeastOneIngredient: 'הוסף לפחות מרכיב אחד.',
    somethingWentWrong: 'משהו השתבש.',
    aiSuggestion: 'הצעת AI',
    noAISuggestions: 'אין עדיין הצעות AI.',
    addToMyRecipes: 'הוסף למתכונים שלי',
    addedToRecipes: 'נוסף',
    adding: 'מוסיף…',
    viewRecipe: 'צפה במתכון',
    all: 'הכל',
    favoritesTab: 'מועדפים',
    add: 'הוסף',
    noFavorites: 'אין מועדפים',
    noFavoritesHint: 'סמן מתכון בכוכב כדי לראות אותו כאן',
    emptyCookbookTitle: 'ספר המתכונים שלך ריק',
    emptyCookbookSubtitle: 'הדבק מתכון ואנו נתרגם ונתאים מרכיבים לשוק שלך.',
    alreadyOnList: 'המתכון כבר ברשימת הקניות',
    addToFavorites: 'הוסף למועדפים',
    removeFromFavorites: 'הסר ממועדפים',
    back: 'חזרה',
    adaptRecipe: 'התאם מתכון',
    relocalize: 'התאם למיקום',
    relocalizeHint: 'תרגום והתאמה מחדש לפי ההגדרות הנוכחיות שלך',
    relocalized: 'המתכון עודכן למיקום',
    failedToRelocalize: 'נכשלה התאמה מחדש',
    original: 'מקורי',
    vegetarian: 'צמחוני',
    vegan: 'טבעוני',
    dairyFree: 'ללא חלב',
    glutenFree: 'ללא גלוטן',
    kosher: 'כשר',
    halal: 'חלאל',
    nutFree: 'ללא אגוזים',
    lowSodium: 'דל נתרן',
    adapting: 'מתאים…',
    cannotAdapt: 'לא ניתן להתאים מתכון זה במלואו ל',
    chooseOption: 'בחר אחת מהאפשרויות:',
    generate: 'צור',
    close: 'סגור',
    translationInProgress: 'התרגום בתהליך — התוכן יופיע בקרוב.',
    notes: 'הערות',
    adaptationSummary: 'מה שינינו',
    ingredients: 'מרכיבים',
    alternativesFor: 'חלופות ל',
    loadingAlternatives: 'טוען חלופות…',
    noAlternativesFound: 'לא נמצאו חלופות.',
    ingredientAlternatives: 'חלופות למרכיב',
    usesOneToken: 'משתמש ב־1 טוקן',
    enableIngredientLookup: 'הפעל חלופות למרכיבים (משתמש בקרדיטים)',
    translated: 'מתורגם',
    originalLabel: 'מקורי',
    instructions: 'הוראות',
    ingredientSubstitutions: 'תחליפי מרכיבים',
    myNotes: 'ההערות שלי',
    notesPlaceholder: 'הוסף הערות, טיפים או שינויים…',
    saveNotes: 'שמור הערות',
    recipeNotFound: 'המתכון לא נמצא',
    servings: 'מנות',
    prepTime: 'זמן הכנה',
    cookTime: 'זמן בישול',
    failedToAdapt: 'ההתאמה נכשלה.',
    failedToGenerateVariant: 'יצירת הגרסה נכשלה.',
    backToOriginal: 'חזרה למקורי',
    applyAdaptations: 'החל',
    removeVariant: 'הסר גרסה',
    showOriginal: 'הצג מקור',
    hideOriginal: 'הסתר מקור',
    addRecipePhoto: 'הוסף תמונת מתכון',
    generateRecipePhoto: 'צור תמונה',
    uploadRecipePhoto: 'העלה תמונה',
    removeRecipePhoto: 'הסר תמונה',
    recipe: 'מתכון',
    recipesCount: 'מתכונים',
    listEmpty: 'הרשימה ריקה',
    loadingIngredients: 'טוען מרכיבים…',
    betterSubstitute: 'תחליף טוב יותר…',
    save: 'שמור',
    suggestSubstitute: 'הצע תחליף טוב יותר',
    clearList: 'נקה רשימה',
    print: 'הדפס',
    sent: 'נשלח!',
    sendToEmail: 'שלח לאימייל',
    sendFailed: 'השליחה נכשלה',
    of: 'מתוך',
    addRecipesToSeeIngredients: 'הוסף מתכונים כדי לראות מרכיבים',
    failedToClearList: 'ניקוי הרשימה נכשל',
  },
  pl: {
    loading: 'Ładowanie…',
    appTitle: 'Tłumacz przepisów',
    tagline: 'Tłumacz przepisy na swój język',
    login: 'Zaloguj',
    register: 'Rejestracja',
    email: 'E-mail',
    password: 'Hasło',
    confirmPassword: 'Powtórz hasło',
    showPassword: 'Pokaż hasło',
    hidePassword: 'Ukryj hasło',
    passwordsMismatch: 'Hasła nie są takie same',
    passwordTooShort: 'Hasło musi mieć co najmniej 8 znaków',
    logInButton: 'Zaloguj →',
    createAccountButton: 'Utwórz konto →',
    appSubtitle: 'Tłumaczenie przepisów',
    shoppingList: 'Lista zakupów',
    recipesQuota: 'Przepisy: {{used}}/{{limit}}',
    recipesQuotaUnlimited: 'Przepisy: ∞',
    settings: 'Ustawienia',
    logOut: 'Wyloguj',
    translationAndLocation: 'Tłumaczenie i lokalizacja',
    appLanguage: 'Język aplikacji / strony',
    recipeLanguage: 'Język przepisów',
    cookingAndDiet: 'Gotowanie i dieta',
    defaultServingsLabel: 'Zwykle gotuję dla…',
    defaultServingsHint: 'Używane jako domyślne przy skalowaniu przepisów (wkrótce).',
    people: 'osób',
    allergensToAvoid: 'Alergeny do unikania',
    otherAllergens: 'Inne alergeny (własny tekst)',
    otherAllergensPlaceholder: 'np. kiwi, truskawki, konkretna marka…',
    otherAllergensHint: 'Będziemy traktować to jako listę „unikaj” (best effort) przy podpowiedziach/zmianach przepisów.',
    optional: 'opcjonalne',
    sourceLanguage: 'Język źródłowy',
    translateTo: 'Tłumacz na',
    language: 'Język',
    country: 'Kraj',
    city: 'Miasto',
    hintLanguage: 'np. pl',
    hintCountry: 'np. PL',
    hintCity: 'np. Wrocław',
    saveSettings: 'Zapisz ustawienia',
    saving: 'Zapisywanie…',
    saved: 'Zapisano',
    account: 'Konto',
    joined: 'Dołączył/a',
    verified: 'zweryfikowany',
    unverified: 'niezweryfikowany',
    resendVerification: 'Wyślij ponownie e-mail weryfikacyjny',
    deleteAccount: 'Usuń konto',
    deleteAccountConfirm: 'Trwale usuń konto i wszystkie przepisy. Wpisz DELETE, aby potwierdzić.',
    typeDelete: 'Wpisz DELETE',
    deleting: 'Usuwanie…',
    deleteAccountButton: 'Usuń konto',
    fetchStarterRecipes: 'Przepisy startowe',
    fetchStarterRecipesHint: 'Dodaj 3 przepisy startowe od znanych kucharzy w Twoim kraju, jeśli nie masz żadnych (np. po pominięciu rejestracji).',
    fetchStarterRecipesButton: 'Pobierz przepisy startowe',
    fetchStarterRecipesDone: 'Przepisy startowe dodane (lub już je masz).',
    addRecipe: 'Dodaj przepis',
    pasteRecipeUrlOrText: 'Wklej link lub tekst przepisu',
    pasteText: 'Wklej tekst',
    pasteUrl: 'Wklej link',
    placeholderRecipe: 'Wklej tutaj przepis…',
    translating: 'Tłumaczenie…',
    translatingNote: 'Tłumaczenie… może potrwać chwilę.',
    cancel: 'Anuluj',
    translateButton: 'Tłumacz →',
    urlError: 'Nie udało się pobrać linku. Sprawdź i spróbuj ponownie.',
    urlInvalid: 'Wpisz poprawny adres URL (http:// lub https://)',
    emailVerification: 'Weryfikacja e-mail',
    checkingToken: 'Sprawdzanie tokenu…',
    verifySuccess: 'E-mail zweryfikowany. Możesz korzystać z aplikacji.',
    verifyError: 'Weryfikacja e-mail nie powiodła się.',
    missingToken: 'Brak tokenu weryfikacji.',
    verificationEmailSent: 'Wysłano e-mail weryfikacyjny. Sprawdź skrzynkę odbiorczą.',
    goToApp: 'Przejdź do aplikacji',
    backToHome: 'Strona główna',
    onShoppingList: 'Na liście zakupów',
    addToList: 'Dodaj do listy',
    favorites: 'ulubione',
    deleteRecipe: 'Usuń przepis',
    addYourFirstRecipe: 'Dodaj swój pierwszy przepis',
    myRecipes: 'Moje przepisy',
    noRecipes: 'Brak przepisów',
    searchRecipes: 'Szukaj przepisów…',
    search: 'Szukaj',
    clear: 'Wyczyść',
    noSearchResults: 'Brak przepisów pasujących do wyszukiwania.',
    whatCanIMake: 'Co mogę zrobić?',
    whatCanIMakeNav: 'Co mogę zrobić?',
    whatCanIMakeHint: 'Wpisz składniki, które masz — znajdziemy pasujące przepisy.',
    ingredientsIHave: 'Składniki, które mam',
    ingredientsPlaceholder: 'np. kurczak, cytryna, ryż',
    ingredientsCommaOrNewline: 'Oddziel przecinkiem lub nową linią.',
    dietFilters: 'Dieta',
    assumePantry: 'Zakładam, że mam podstawy (sól, cukier, olej itd.)',
    source: 'Szukaj w',
    findRecipes: 'Znajdź przepisy',
    finding: 'Szukam…',
    youHaveEverything: 'Masz wszystko do przygotowania.',
    missingIngredients: 'Brakuje',
    iHaveThis: 'Mam to',
    noMatchingRecipes: 'Brak pasujących przepisów.',
    tryMoreIngredientsOrSwitchAI: 'Dodaj więcej składników lub przełącz na sugestię AI.',
    addAtLeastOneIngredient: 'Dodaj co najmniej jeden składnik.',
    somethingWentWrong: 'Coś poszło nie tak.',
    aiSuggestion: 'Sugestia AI',
    noAISuggestions: 'Brak sugestii AI.',
    addToMyRecipes: 'Dodaj do moich przepisów',
    addedToRecipes: 'Dodano',
    adding: 'Dodawanie…',
    viewRecipe: 'Zobacz przepis',
    all: 'Wszystkie',
    favoritesTab: 'Ulubione',
    add: 'Dodaj',
    noFavorites: 'Brak ulubionych',
    noFavoritesHint: 'Oznacz przepis gwiazdką, aby zobaczyć go tutaj',
    emptyCookbookTitle: 'Twoja książka kucharska jest pusta',
    emptyCookbookSubtitle: 'Wklej przepis, a przetłumaczymy go i dostosujemy składniki do Twojego rynku.',
    alreadyOnList: 'Przepis jest już na liście zakupów',
    addToFavorites: 'Dodaj do ulubionych',
    removeFromFavorites: 'Usuń z ulubionych',
    back: 'Wstecz',
    adaptRecipe: 'Dostosuj przepis',
    relocalize: 'Lokalizuj ponownie',
    relocalizeHint: 'Przetłumacz i zlokalizuj ponownie wg obecnych ustawień',
    relocalized: 'Przepis zlokalizowany ponownie',
    failedToRelocalize: 'Nie udało się zlokalizować ponownie',
    original: 'Oryginał',
    vegetarian: 'Wegetariański',
    vegan: 'Wegański',
    dairyFree: 'Bez nabiału',
    glutenFree: 'Bez glutenu',
    kosher: 'Koszerny',
    halal: 'Halal',
    nutFree: 'Bez orzechów',
    lowSodium: 'Niskosodowy',
    adapting: 'Dostosowuję…',
    cannotAdapt: 'Przepisu nie można w pełni dostosować do',
    chooseOption: 'Wybierz jedną z opcji:',
    generate: 'Wygeneruj',
    close: 'Zamknij',
    translationInProgress: 'Tłumaczenie w toku — treść pojawi się wkrótce.',
    notes: 'Uwagi',
    adaptationSummary: 'Co zmieniono',
    ingredients: 'Składniki',
    alternativesFor: 'Alternatywy dla',
    loadingAlternatives: 'Ładowanie alternatyw…',
    noAlternativesFound: 'Nie znaleziono alternatyw.',
    ingredientAlternatives: 'Alternatywy składnika',
    usesOneToken: 'Zużywa 1 token',
    enableIngredientLookup: 'Włącz alternatywy składników (zużywa kredyty)',
    translated: 'Przetłumaczono',
    originalLabel: 'Oryginał',
    instructions: 'Przygotowanie',
    ingredientSubstitutions: 'Zamienniki składników',
    myNotes: 'Moje notatki',
    notesPlaceholder: 'Dodaj notatki, wskazówki lub modyfikacje…',
    saveNotes: 'Zapisz notatki',
    recipeNotFound: 'Nie znaleziono przepisu',
    servings: 'Porcje',
    prepTime: 'Czas przygotowania',
    cookTime: 'Czas gotowania',
    failedToAdapt: 'Dostosowanie nie powiodło się.',
    failedToGenerateVariant: 'Generowanie wariantu nie powiodło się.',
    backToOriginal: 'Wróć do oryginału',
    applyAdaptations: 'Zastosuj',
    removeVariant: 'Usuń wersję',
    showOriginal: 'Pokaż oryginał',
    hideOriginal: 'Ukryj oryginał',
    addRecipePhoto: 'Dodaj zdjęcie przepisu',
    generateRecipePhoto: 'Wygeneruj zdjęcie',
    uploadRecipePhoto: 'Prześlij zdjęcie',
    removeRecipePhoto: 'Usuń zdjęcie',
    recipe: 'przepis',
    recipesCount: 'przepisy',
    listEmpty: 'Lista jest pusta',
    loadingIngredients: 'Ładowanie składników…',
    betterSubstitute: 'Lepszy zamiennik…',
    save: 'Zapisz',
    suggestSubstitute: 'Zaproponuj lepszy zamiennik',
    clearList: 'Wyczyść listę',
    print: 'Drukuj',
    sent: 'Wysłano!',
    sendToEmail: 'Wyślij na e-mail',
    sendFailed: 'Wysyłka nie powiodła się',
    of: 'z',
    addRecipesToSeeIngredients: 'Dodaj przepisy, aby zobaczyć składniki',
    failedToClearList: 'Nie udało się wyczyścić listy',
  },
}

const LanguageContext = createContext(null)

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState(() => {
    try {
      const stored = localStorage.getItem(STORAGE_KEY)
      if (stored === 'en' || stored === 'he' || stored === 'pl') return stored
    } catch (_) {}
    return 'en'
  })

  useEffect(() => {
    try {
      localStorage.setItem(STORAGE_KEY, lang)
    } catch (_) {}
    const html = document.documentElement
    html.setAttribute('lang', lang === 'he' ? 'he' : lang === 'pl' ? 'pl' : 'en')
    html.setAttribute('dir', lang === 'he' ? 'rtl' : 'ltr')
  }, [lang])

  function setLang(l) {
    if (l === 'en' || l === 'he' || l === 'pl') setLangState(l)
  }

  function t(key, vars = {}) {
    const raw = translations[lang]?.[key] ?? translations.en[key] ?? key
    if (typeof raw !== 'string') return key
    return Object.entries(vars).reduce((s, [k, v]) => s.replace(new RegExp(`{{${k}}}`, 'g'), String(v)), raw)
  }

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const ctx = useContext(LanguageContext)
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider')
  return ctx
}
